image: node:16.13.2

stages:
  - build
  - docker

variables:
  GIT_SUBMODULE_STRATEGY: recursive

.job_template: &job_rules
  rules:
    # dev
    - if: '$CI_COMMIT_TAG =~ /^dev.*$/'
      variables:
        ENV: 'DEV'
        IMAGE_TAG_NAME: '$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG'

    # qa
    - if: '$CI_COMMIT_TAG =~ /^qa.*$/'
      variables:
        ENV: 'QA'
        IMAGE_TAG_NAME: '$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG'

    # prd
    - if: '$CI_COMMIT_TAG =~ /^v.*$/'
      variables:
        ENV: 'PRD'
        IMAGE_TAG_NAME: 'asia.gcr.io/megaplay/lego/frontend/$CI_PROJECT_NAME:$CI_COMMIT_TAG'

build:
  stage: build
  <<: *job_rules
  script:
    - yarn install
    - yarn run build
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules/
  artifacts:
    name: '$CI_COMMIT_TAG'
    paths:
      - dist/

docker:
  stage: docker
  <<: *job_rules
  image: docker:latest
  services:
    - docker:dind
  cache: {}
  script:
    - echo $ENV
    - if [ "$ENV" == "PRD" ]; then
    - cat $GCR_KEY | docker login -u _json_key --password-stdin https://asia.gcr.io
    - else
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - fi
    - docker build --pull -t $IMAGE_TAG_NAME .
    - docker push $IMAGE_TAG_NAME
    - echo $IMAGE_TAG_NAME
